#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum Element {
    Actinium,
    Aluminium,
    Americium,
    Antimony,
    Argon,
    Arsenic,
    Astatine,
    Barium,
    Berkelium,
    Beryllium,
    Bismuth,
    Bohrium,
    Boron,
    Bromine,
    Cadmium,
    Caesium,
    Calcium,
    Californium,
    Carbon,
    Cerium,
    Chlorine,
    Chromium,
    Cobalt,
    Copernicium,
    Copper,
    Curium,
    Darmstadtium,
    Dubnium,
    Dysprosium,
    Einsteinium,
    Erbium,
    Europium,
    Fermium,
    Flerovium,
    Fluorine,
    Francium,
    Gadolinium,
    Gallium,
    Germanium,
    Gold,
    Hafnium,
    Hassium,
    Helium,
    Holmium,
    Hydrogen,
    Indium,
    Iodine,
    Iridium,
    Iron,
    Krypton,
    Lanthanum,
    Lawrencium,
    Lead,
    Lithium,
    Livermorium,
    Lutetium,
    Magnesium,
    Manganese,
    Meitnerium,
    Mendelevium,
    Mercury,
    Molybdenum,
    Moscovium,
    Neodymium,
    Neon,
    Neptunium,
    Nickel,
    Nihonium,
    Niobium,
    Nitrogen,
    Nobelium,
    Oganesson,
    Osmium,
    Oxygen,
    Palladium,
    Phosphorus,
    Platinum,
    Plutonium,
    Polonium,
    Potassium,
    Praseodymium,
    Promethium,
    Protactinium,
    Radium,
    Radon,
    Rhenium,
    Rhodium,
    Roentgenium,
    Rubidium,
    Ruthenium,
    Rutherfordium,
    Samarium,
    Scandium,
    Seaborgium,
    Selenium,
    Silicon,
    Silver,
    Sodium,
    Strontium,
    Sulfur,
    Tantalum,
    Technetium,
    Tellurium,
    Tennessine,
    Terbium,
    Thallium,
    Thorium,
    Thulium,
    Tin,
    Titanium,
    Tungsten,
    Unbinilium,
    Unbiunium,
    Ununennium,
    Uranium,
    Vanadium,
    Xenon,
    Ytterbium,
    Yttrium,
    Zinc,
    Zirconium,
}

pub fn symbol_to_element(symbol: &str) -> Option<Element> {
    match symbol {
        "Ac" => Some(Element::Actinium),
        "Ag" => Some(Element::Silver),
        "Al" => Some(Element::Aluminium),
        "Am" => Some(Element::Americium),
        "Ar" => Some(Element::Argon),
        "As" => Some(Element::Arsenic),
        "At" => Some(Element::Astatine),
        "Au" => Some(Element::Gold),
        "B" => Some(Element::Boron),
        "Ba" => Some(Element::Barium),
        "Be" => Some(Element::Beryllium),
        "Bh" => Some(Element::Bohrium),
        "Bi" => Some(Element::Bismuth),
        "Bk" => Some(Element::Berkelium),
        "Br" => Some(Element::Bromine),
        "C" => Some(Element::Carbon),
        "Ca" => Some(Element::Calcium),
        "Cd" => Some(Element::Cadmium),
        "Ce" => Some(Element::Cerium),
        "Cf" => Some(Element::Californium),
        "Cl" => Some(Element::Chlorine),
        "Cm" => Some(Element::Curium),
        "Co" => Some(Element::Cobalt),
        "Cr" => Some(Element::Chromium),
        "Cs" => Some(Element::Caesium),
        "Cu" => Some(Element::Copper),
        "Db" => Some(Element::Dubnium),
        "Ds" => Some(Element::Darmstadtium),
        "Dy" => Some(Element::Dysprosium),
        "Er" => Some(Element::Erbium),
        "Es" => Some(Element::Einsteinium),
        "Eu" => Some(Element::Europium),
        "F" => Some(Element::Fluorine),
        "Fe" => Some(Element::Iron),
        "Fm" => Some(Element::Fermium),
        "Fr" => Some(Element::Francium),
        "Ga" => Some(Element::Gallium),
        "Gd" => Some(Element::Gadolinium),
        "Ge" => Some(Element::Germanium),
        "H" => Some(Element::Hydrogen),
        "He" => Some(Element::Helium),
        "Hf" => Some(Element::Hafnium),
        "Hg" => Some(Element::Mercury),
        "Ho" => Some(Element::Holmium),
        "Hs" => Some(Element::Hassium),
        "I" => Some(Element::Iodine),
        "In" => Some(Element::Indium),
        "Ir" => Some(Element::Iridium),
        "K" => Some(Element::Potassium),
        "Kr" => Some(Element::Krypton),
        "La" => Some(Element::Lanthanum),
        "Li" => Some(Element::Lithium),
        "Lr" => Some(Element::Lawrencium),
        "Lu" => Some(Element::Lutetium),
        "Md" => Some(Element::Mendelevium),
        "Mg" => Some(Element::Magnesium),
        "Mn" => Some(Element::Manganese),
        "Mo" => Some(Element::Molybdenum),
        "Mt" => Some(Element::Meitnerium),
        "N" => Some(Element::Nitrogen),
        "Na" => Some(Element::Sodium),
        "Nb" => Some(Element::Niobium),
        "Nd" => Some(Element::Neodymium),
        "Ne" => Some(Element::Neon),
        "Ni" => Some(Element::Nickel),
        "No" => Some(Element::Nobelium),
        "Np" => Some(Element::Neptunium),
        "O" => Some(Element::Oxygen),
        "Os" => Some(Element::Osmium),
        "P" => Some(Element::Phosphorus),
        "Pa" => Some(Element::Protactinium),
        "Pb" => Some(Element::Lead),
        "Pd" => Some(Element::Palladium),
        "Pm" => Some(Element::Promethium),
        "Po" => Some(Element::Polonium),
        "Pr" => Some(Element::Praseodymium),
        "Pt" => Some(Element::Platinum),
        "Pu" => Some(Element::Plutonium),
        "Ra" => Some(Element::Radium),
        "Rb" => Some(Element::Rubidium),
        "Re" => Some(Element::Rhenium),
        "Rf" => Some(Element::Rutherfordium),
        "Rg" => Some(Element::Roentgenium),
        "Rh" => Some(Element::Rhodium),
        "Rn" => Some(Element::Radon),
        "Ru" => Some(Element::Ruthenium),
        "S" => Some(Element::Sulfur),
        "Sb" => Some(Element::Antimony),
        "Sc" => Some(Element::Scandium),
        "Se" => Some(Element::Selenium),
        "Sg" => Some(Element::Seaborgium),
        "Si" => Some(Element::Silicon),
        "Sm" => Some(Element::Samarium),
        "Sn" => Some(Element::Tin),
        "Sr" => Some(Element::Strontium),
        "Ta" => Some(Element::Tantalum),
        "Tb" => Some(Element::Terbium),
        "Tc" => Some(Element::Technetium),
        "Te" => Some(Element::Tellurium),
        "Th" => Some(Element::Thorium),
        "Ti" => Some(Element::Titanium),
        "Tl" => Some(Element::Thallium),
        "Tm" => Some(Element::Thulium),
        "U" => Some(Element::Uranium),
        "Ubn" => Some(Element::Unbinilium),
        "Ubu" => Some(Element::Unbiunium),
        "Uue" => Some(Element::Ununennium),
        "Cn" => Some(Element::Copernicium),
        "Lv" => Some(Element::Livermorium),
        "Og" => Some(Element::Oganesson),
        "Mc" => Some(Element::Moscovium),
        "Fl" => Some(Element::Flerovium),
        "Ts" => Some(Element::Tennessine),
        "Nh" => Some(Element::Nihonium),
        "V" => Some(Element::Vanadium),
        "W" => Some(Element::Tungsten),
        "Xe" => Some(Element::Xenon),
        "Y" => Some(Element::Yttrium),
        "Yb" => Some(Element::Ytterbium),
        "Zn" => Some(Element::Zinc),
        "Zr" => Some(Element::Zirconium),
        _ => None,
    }
}
